after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[workspace-to-monitor-force-assignment]
    1 = 'secondary'
    2 = 'secondary'
    3 = 'secondary'
    4 = 'secondary'
    5 = 'secondary'
    11 = 'secondary'
    12 = 'secondary'
    13 = 'secondary'
    14 = 'secondary'
    6 = ['main', 'secondary']
    7 = ['main', 'secondary']
    8 = ['main', 'secondary']
    9 = ['main', 'secondary']
    10 = ['main', 'secondary']
    15 = ['main', 'secondary']
    16 = ['main', 'secondary']
    17 = ['main', 'secondary']

[mode.main.binding]
    ctrl-alt-s = 'mode service'
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    alt-leftSquareBracket= 'workspace prev'
    alt-rightSquareBracket= 'workspace next'
    alt-backtick = 'focus-back-and-forth'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    alt-ctrl-left = 'focus left'
    alt-ctrl-down = 'focus down'
    alt-ctrl-up = 'focus up'
    alt-ctrl-right = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    alt-shift-left = 'move left'
    alt-shift-down = 'move down'
    alt-shift-up = 'move up'
    alt-shift-right = 'move right'

    alt-t = 'join-with left'
    alt-y = 'join-with down'

    alt-f = 'fullscreen'

    alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
    alt-d = 'layout tiles horizontal horizontal' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    
    alt-shift-g = 'balance-sizes'
    alt-shift-f = 'flatten-workspace-tree'

    # Left
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-z = 'workspace 11'
    alt-x = 'workspace 12'
    alt-c = 'workspace 13'
    alt-v = 'workspace 14'
    
    # Right
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'
    alt-b = 'workspace 15'
    alt-n = 'workspace 16'
    alt-m = 'workspace 17'

    # Left
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-z = 'move-node-to-workspace 11'
    alt-shift-x = 'move-node-to-workspace 12'
    alt-shift-c = 'move-node-to-workspace 13'
    alt-shift-v = 'move-node-to-workspace 14'
    
    # Right
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'
    alt-shift-b = 'move-node-to-workspace 15'
    alt-shift-n = 'move-node-to-workspace 16'
    alt-shift-m = 'move-node-to-workspace 17'

[mode.service.binding]
    ctrl-alt-s = 'mode main'
    alt-shift-esc = ['reload-config', 'mode main']
    alt-shift-r = ['flatten-workspace-tree', 'mode main'] # reset layout
    alt-shift-f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    alt-shift-backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    alt-shift-down = 'volume down'
    alt-shift-up = 'volume up'
    alt-tab = 'workspace-back-and-forth'                                          
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'                
    alt-shift-c = 'reload-config'
                                                                                   
 # 'service' binding mode declaration.                                             
 # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes        
